# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 11:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(null=True)),
                ('chk', models.IntegerField(null=True)),
                ('ein', models.IntegerField(null=True)),
                ('eout', models.IntegerField(null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'maps_node',
            },
        ),
        migrations.CreateModel(
            name='roads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(null=True)),
                ('target', models.IntegerField(null=True)),
                ('speed_kmh', models.SmallIntegerField()),
                ('dist_km', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cost_min', models.DecimalField(decimal_places=5, max_digits=10)),
                ('street_type', models.CharField(max_length=6, null=True)),
                ('ngduid', models.IntegerField()),
                ('the_geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'db_table': 'maps_roads',
            },
        ),
    ]
