# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_dd_node_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dd_node',
            name='chk',
        ),
        migrations.RemoveField(
            model_name='dd_node',
            name='cnt',
        ),
        migrations.RemoveField(
            model_name='dd_node',
            name='ein',
        ),
        migrations.RemoveField(
            model_name='dd_node',
            name='eout',
        ),
        migrations.RemoveField(
            model_name='dd_node',
            name='seq',
        ),
    ]
