# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20170825_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dd_node',
            name='node',
        ),
    ]
