# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_remove_dd_node_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='dd_poly',
            name='session',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
