# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_dd_poly_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dd_node',
            name='session',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dd_poly',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.dd_node'),
        ),
    ]
