# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20170825_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dd_poly',
            name='id',
        ),
        migrations.AlterField(
            model_name='dd_poly',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maps.dd_node'),
        ),
    ]
